# Generated by Django 4.2 on 2023-04-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_indentificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='indentificador',
            new_name='identificador',
        ),
    ]
